//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPRBConsole.SprbSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SprbSoap.ZECOLLECTSAP")]
    public interface ZECOLLECTSAP {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZfiGetServicecodeCliente no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiGetServicecodeCl" +
            "ienteRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1 ZfiGetServicecodeCliente(SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiGetServicecodeCl" +
            "ienteRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1> ZfiGetServicecodeClienteAsync(SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZfiGetCarteraCliente no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiGetCarteraClient" +
            "eRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1 ZfiGetCarteraCliente(SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiGetCarteraClient" +
            "eRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1> ZfiGetCarteraClienteAsync(SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZfiNotifyPaymentD no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiNotifyPaymentDRe" +
            "quest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1 ZfiNotifyPaymentD(SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZECOLLECTSAP:ZfiNotifyPaymentDRe" +
            "quest", ReplyAction="*")]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1> ZfiNotifyPaymentDAsync(SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiGetServicecodeCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitycodeField;
        
        private string reference1Field;
        
        private string reference2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Entitycode {
            get {
                return this.entitycodeField;
            }
            set {
                this.entitycodeField = value;
                this.RaisePropertyChanged("Entitycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Reference1 {
            get {
                return this.reference1Field;
            }
            set {
                this.reference1Field = value;
                this.RaisePropertyChanged("Reference1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Reference2 {
            get {
                return this.reference2Field;
            }
            set {
                this.reference2Field = value;
                this.RaisePropertyChanged("Reference2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiGetServicecodeClienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        private string retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
                this.RaisePropertyChanged("Retorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiGetServicecodeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiGetServicecodeCliente ZfiGetServicecodeCliente;
        
        public ZfiGetServicecodeClienteRequest() {
        }
        
        public ZfiGetServicecodeClienteRequest(SPRBConsole.SprbSoap.ZfiGetServicecodeCliente ZfiGetServicecodeCliente) {
            this.ZfiGetServicecodeCliente = ZfiGetServicecodeCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiGetServicecodeClienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse ZfiGetServicecodeClienteResponse;
        
        public ZfiGetServicecodeClienteResponse1() {
        }
        
        public ZfiGetServicecodeClienteResponse1(SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse ZfiGetServicecodeClienteResponse) {
            this.ZfiGetServicecodeClienteResponse = ZfiGetServicecodeClienteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiGetCarteraCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitycodeField;
        
        private string passwordField;
        
        private string reference1Field;
        
        private string reference2Field;
        
        private string servicecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Entitycode {
            get {
                return this.entitycodeField;
            }
            set {
                this.entitycodeField = value;
                this.RaisePropertyChanged("Entitycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Reference1 {
            get {
                return this.reference1Field;
            }
            set {
                this.reference1Field = value;
                this.RaisePropertyChanged("Reference1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Reference2 {
            get {
                return this.reference2Field;
            }
            set {
                this.reference2Field = value;
                this.RaisePropertyChanged("Reference2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Servicecode {
            get {
                return this.servicecodeField;
            }
            set {
                this.servicecodeField = value;
                this.RaisePropertyChanged("Servicecode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiGetCarteraClienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseField;
        
        private string returncodeField;
        
        private string returndescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Returncode {
            get {
                return this.returncodeField;
            }
            set {
                this.returncodeField = value;
                this.RaisePropertyChanged("Returncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Returndesc {
            get {
                return this.returndescField;
            }
            set {
                this.returndescField = value;
                this.RaisePropertyChanged("Returndesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiGetCarteraClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiGetCarteraCliente ZfiGetCarteraCliente;
        
        public ZfiGetCarteraClienteRequest() {
        }
        
        public ZfiGetCarteraClienteRequest(SPRBConsole.SprbSoap.ZfiGetCarteraCliente ZfiGetCarteraCliente) {
            this.ZfiGetCarteraCliente = ZfiGetCarteraCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiGetCarteraClienteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse ZfiGetCarteraClienteResponse;
        
        public ZfiGetCarteraClienteResponse1() {
        }
        
        public ZfiGetCarteraClienteResponse1(SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse ZfiGetCarteraClienteResponse) {
            this.ZfiGetCarteraClienteResponse = ZfiGetCarteraClienteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiNotifyPaymentD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankprocessdateField;
        
        private string entitycodeField;
        
        private string finameField;
        
        private string paymentchannelField;
        
        private string servicecodeField;
        
        private string ticketidField;
        
        private string transcycleField;
        
        private string trazabilitycodeField;
        
        private string xmlreferencearrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bankprocessdate {
            get {
                return this.bankprocessdateField;
            }
            set {
                this.bankprocessdateField = value;
                this.RaisePropertyChanged("Bankprocessdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Entitycode {
            get {
                return this.entitycodeField;
            }
            set {
                this.entitycodeField = value;
                this.RaisePropertyChanged("Entitycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Finame {
            get {
                return this.finameField;
            }
            set {
                this.finameField = value;
                this.RaisePropertyChanged("Finame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Paymentchannel {
            get {
                return this.paymentchannelField;
            }
            set {
                this.paymentchannelField = value;
                this.RaisePropertyChanged("Paymentchannel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Servicecode {
            get {
                return this.servicecodeField;
            }
            set {
                this.servicecodeField = value;
                this.RaisePropertyChanged("Servicecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Ticketid {
            get {
                return this.ticketidField;
            }
            set {
                this.ticketidField = value;
                this.RaisePropertyChanged("Ticketid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Transcycle {
            get {
                return this.transcycleField;
            }
            set {
                this.transcycleField = value;
                this.RaisePropertyChanged("Transcycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Trazabilitycode {
            get {
                return this.trazabilitycodeField;
            }
            set {
                this.trazabilitycodeField = value;
                this.RaisePropertyChanged("Trazabilitycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Xmlreferencearray {
            get {
                return this.xmlreferencearrayField;
            }
            set {
                this.xmlreferencearrayField = value;
                this.RaisePropertyChanged("Xmlreferencearray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiNotifyPaymentDResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returncodeField;
        
        private string returndescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Returncode {
            get {
                return this.returncodeField;
            }
            set {
                this.returncodeField = value;
                this.RaisePropertyChanged("Returncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Returndesc {
            get {
                return this.returndescField;
            }
            set {
                this.returndescField = value;
                this.RaisePropertyChanged("Returndesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiNotifyPaymentDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiNotifyPaymentD ZfiNotifyPaymentD;
        
        public ZfiNotifyPaymentDRequest() {
        }
        
        public ZfiNotifyPaymentDRequest(SPRBConsole.SprbSoap.ZfiNotifyPaymentD ZfiNotifyPaymentD) {
            this.ZfiNotifyPaymentD = ZfiNotifyPaymentD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiNotifyPaymentDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse ZfiNotifyPaymentDResponse;
        
        public ZfiNotifyPaymentDResponse1() {
        }
        
        public ZfiNotifyPaymentDResponse1(SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse ZfiNotifyPaymentDResponse) {
            this.ZfiNotifyPaymentDResponse = ZfiNotifyPaymentDResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZECOLLECTSAPChannel : SPRBConsole.SprbSoap.ZECOLLECTSAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZECOLLECTSAPClient : System.ServiceModel.ClientBase<SPRBConsole.SprbSoap.ZECOLLECTSAP>, SPRBConsole.SprbSoap.ZECOLLECTSAP {
        
        public ZECOLLECTSAPClient() {
        }
        
        public ZECOLLECTSAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZECOLLECTSAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZECOLLECTSAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZECOLLECTSAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1 SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiGetServicecodeCliente(SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest request) {
            return base.Channel.ZfiGetServicecodeCliente(request);
        }
        
        public SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse ZfiGetServicecodeCliente(SPRBConsole.SprbSoap.ZfiGetServicecodeCliente ZfiGetServicecodeCliente1) {
            SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest inValue = new SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest();
            inValue.ZfiGetServicecodeCliente = ZfiGetServicecodeCliente1;
            SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1 retVal = ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiGetServicecodeCliente(inValue);
            return retVal.ZfiGetServicecodeClienteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1> SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiGetServicecodeClienteAsync(SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest request) {
            return base.Channel.ZfiGetServicecodeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetServicecodeClienteResponse1> ZfiGetServicecodeClienteAsync(SPRBConsole.SprbSoap.ZfiGetServicecodeCliente ZfiGetServicecodeCliente) {
            SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest inValue = new SPRBConsole.SprbSoap.ZfiGetServicecodeClienteRequest();
            inValue.ZfiGetServicecodeCliente = ZfiGetServicecodeCliente;
            return ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiGetServicecodeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1 SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiGetCarteraCliente(SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest request) {
            return base.Channel.ZfiGetCarteraCliente(request);
        }
        
        public SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse ZfiGetCarteraCliente(SPRBConsole.SprbSoap.ZfiGetCarteraCliente ZfiGetCarteraCliente1) {
            SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest inValue = new SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest();
            inValue.ZfiGetCarteraCliente = ZfiGetCarteraCliente1;
            SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1 retVal = ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiGetCarteraCliente(inValue);
            return retVal.ZfiGetCarteraClienteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1> SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiGetCarteraClienteAsync(SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest request) {
            return base.Channel.ZfiGetCarteraClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiGetCarteraClienteResponse1> ZfiGetCarteraClienteAsync(SPRBConsole.SprbSoap.ZfiGetCarteraCliente ZfiGetCarteraCliente) {
            SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest inValue = new SPRBConsole.SprbSoap.ZfiGetCarteraClienteRequest();
            inValue.ZfiGetCarteraCliente = ZfiGetCarteraCliente;
            return ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiGetCarteraClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1 SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiNotifyPaymentD(SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest request) {
            return base.Channel.ZfiNotifyPaymentD(request);
        }
        
        public SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse ZfiNotifyPaymentD(SPRBConsole.SprbSoap.ZfiNotifyPaymentD ZfiNotifyPaymentD1) {
            SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest inValue = new SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest();
            inValue.ZfiNotifyPaymentD = ZfiNotifyPaymentD1;
            SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1 retVal = ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiNotifyPaymentD(inValue);
            return retVal.ZfiNotifyPaymentDResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1> SPRBConsole.SprbSoap.ZECOLLECTSAP.ZfiNotifyPaymentDAsync(SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest request) {
            return base.Channel.ZfiNotifyPaymentDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SPRBConsole.SprbSoap.ZfiNotifyPaymentDResponse1> ZfiNotifyPaymentDAsync(SPRBConsole.SprbSoap.ZfiNotifyPaymentD ZfiNotifyPaymentD) {
            SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest inValue = new SPRBConsole.SprbSoap.ZfiNotifyPaymentDRequest();
            inValue.ZfiNotifyPaymentD = ZfiNotifyPaymentD;
            return ((SPRBConsole.SprbSoap.ZECOLLECTSAP)(this)).ZfiNotifyPaymentDAsync(inValue);
        }
    }
}
